from pathlib import Path
import re
root=Path(__file__).parent
source=(root/'outline-source.md').read_text(encoding='utf-8').split('—------------------------------------------------------------------------------------------------------------',1)[1]
locations={1:'Abstract',2:'§1 Introduction',3:'§2 BrainCode',4:'§3 Evaluations',5:'§4 Conclusions and Discussion',6:'AI Disclosure',7:'References',8:'Appendices A–C'}
sub={
'2.1':'§1, Related work', '2.2.1':'§1, Our work and objectives', '2.2.2':'§1, definitions; operational metrics in §3', '2.2.3':'§1, Research questions; answers in §4.1',
'3.1.1':'§2.1, Syntax creation', '3.1.2':'§2.1, final paragraph (three sentences)', '3.2.1':'§2.2, opening paragraph (two sentences)', '3.2.2':'§2.2, Data and loop; Retrieval and checking', '3.2.3':'Figure 2, proposal counts by dataset and type', '3.3.1':'§2.3, Language and glossary', '3.3.2':'§2.3 and Table 1', '3.3.3':'§2.3, task and conversation listings',
'4.1':'§3.1, coverage and diagnostic OpenAI trials', '4.1.2.1':'Table 2, success/failure/error counts and rates', '4.1.2.2':'Figure 3, shared coverage radar',
'4.2.1.1':'Figure 4, left panel', '4.2.1.2':'Figure 4, right panel (side by side)', '4.2.1.3':'Figure 5 and §3.2, type mix including diagnostic o4-mini', '4.2':'§3.2, determinism, qualitative report, and interpretation',
'4.3':'§3.3 and Figure 6, encoding/decoding and qualitative reconstruction', '4.4':'§3.4 and Table 3, all 23 task types and total',
'5.1.1':'§4.1, Agent-created language (RQ2)', '5.1.2':'§4.1, Comparative research (RQ1)', '5.1.3':'§4.1, Reasoning (RQ3)', '5.2':'§4.2, Limitations', '5.3':'§4.3, Future work',
'8.1':'Appendix A, linked Git repository and evidence map', '8.2':'Appendix B, additional visualizations', '8.3.1':'Appendix B and Figure 7 left, both rankings in text', '8.3.2':'Appendix B and Figure 7 right, self-divergence by dataset'}
lines=['# Outline coverage audit','','Source of content: `outline-source.md`, exported from the supplied Google Doc. The manuscript preserves its section order and all substantive requests. The copied outline remains unchanged.','','The table below retains every numbered content item from the outline, including organizational headings. Wording is quoted from the outline; links and assignments are source context, not separate instructions to contact people.','','## Reconciliation with the evidence','','- The outline’s 56/95 GPT constructor suggestions was a preliminary snapshot. Saved current raw trials contain 71/129; the manuscript uses the latter.','- Haiku exceeds both Gemini conditions on the shared sample. The manuscript preserves the proposed construction-model-bias interpretation as a hypothesis, alongside strict versus lenient readings, rather than asserting Gemini beats all Claude models.','- Noun grouping is a central reported problem, but no exhaustive causal coding supports a claim that it is quantitatively the largest source of failures.','- The reasoning decline is explicit. Context load is a hypothesis, not an ablated cause. Clustered analysis and paired item-majority inference differ; both are reported.','- The implemented self-divergence uses arithmetic means, although the initial evaluation design requested harmonic averaging.','- OpenAI models are excluded from the main determinism/expressivity comparison. The outline also requests o4-mini’s type mix; this is retained and marked as a failure-confounded diagnostic.','- Guy’s migration-link placeholder is unfilled in the outline. The repository migration document supplies the evidence for the required three-sentence description.','- No evaluated fine-tuned model exists in the saved results. Preparation and resource limitations are described without inventing an outcome.','- The source qualitative reconstruction report ends mid-sentence. Only its complete, supported analysis is summarized.','- Author names follow the existing Overleaf project (Lia Soffer and Noam Yehezkel). The outline’s assignment to Simon is not treated as evidence of authorship.','','## Item-by-item coverage','','| Outline ID | Original requested content | Manuscript location |','|---|---|---|']
stack=[];count=0
for raw in source.splitlines():
    m=re.match(r'^(\s*)(\d+)\.\s+(.*)$',raw)
    if not m:continue
    level=len(m.group(1))//3
    stack=stack[:level]+[m.group(2)]
    ident='.'.join(stack); content=m.group(3).strip().replace('|','\\|')
    loc=locations.get(int(stack[0]),'Source context')
    for key in sorted(sub,key=len):
        if ident==key or ident.startswith(key+'.'): loc=sub[key]
    lines.append(f'| {ident} | {content} | {loc} |');count+=1
lines+=['',f'**Total numbered content items mapped: {count}.**','','## Grading checklist','','| Rubric area | Evidence in manuscript |','|---|---|','| Research question (10%) | Three explicit questions; objectives defined in §1 and conclusions mapped back in §4.1. |','| Ambition and effort (10%) | Syntax loop, semantic migration, swarm, retrieval, six data sources, multi-model evaluation, and reasoning pipeline. |','| Literature review (20%) | Semantic representations, reasoning/actions, program-aided reasoning, decomposition, formalization, compression, and multi-agent communication; all six datasets and BBEH cited. |','| Method (20%) | Split seeds, sample sizes, frozen versions, model identifiers, metrics, selection/exclusion rules, prompts, decoding settings, and repository evidence map. |','| Results and discussion (20%) | All requested graphs, complete reasoning task table, negative results, qualitative cases, alternative explanations, and statistical limitations. |','| Presentation (20%) | Official ACL style, author-year citations, vector PDF figures, descriptive captions, code examples, and separate back matter. Final rendering and page count recorded in page-budget.md. |','']
(root/'outline-coverage.md').write_text('\n'.join(lines),encoding='utf-8')
print('Mapped',count,'numbered outline items.')
